from pydantic import BaseModel, Field
from typing import Dict, Any, List

class StepExecution(BaseModel):
    """
    Represents a single executable step derived from natural language intent.
    """
    step: int = Field(..., description="The sequential step number, starting from 1.")
    action: str = Field(..., description="The type of action to perform (e.g., 'swap', 'check_balance').")
    params: Dict[str, Any] = Field(default_factory=dict, description="Parameters required for the action.")

class ParsedIntent(BaseModel):
    """
    Represents the full parsed execution plan generated by the LLM or fallback engine.
    """
    rationale: str = Field(..., description="The reasoning behind the generated execution plan.")
    execution_plan: List[StepExecution] = Field(..., description="The ordered list of steps to execute.")
